add validation and  unit tests
BANCUNGUYE66/Blog-app pull request #3
Opened 2023-07-14 14:46 UTC by BANCUNGUYE66

## validations and model specs

###  Use validations for models
For the User model:
- [x] Name must not be blank.
- [x] PostsCounter must be an integer greater than or equal to zero.

### Write unit tests for models
For the Post model:
- [x] Title must not be blank.
- [x] Title must not exceed 250 characters.
- [x] CommentsCounter must be an integer greater than or equal to zero.
- [x] LikesCounter must be an integer greater than or equal to zero.

2023-07-14 15:08 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @BANCUNGUYE66 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow Gitflow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-14 15:08 UTC, tresorsawasawa commented on spec/models/user_spec.rb
> +  end
- [x] As required for the project to test any custom methods in the models, kindly ensure that you also add test(s)  to the `#recent_posts` method in the `User` model

2023-07-14 15:08 UTC, tresorsawasawa commented on spec/models/post_spec.rb
> +  end
- [x] As required for the project to test any custom methods in the models, kindly ensure that you also add test(s)  to the `#recent_comments` and `#update_posts_counter` methods in the `Post` model.

-- [ **OPTIONAL** ] To make your tests be more descriptive, I think it would be better if you use the same syntax like the one in the `spec/models/user_spec.rb` file. i.e.
```ruby
...
  it 'should check the title be present' do
      subject.title = nil
      expect(subject).to_not be_valid
    end

    it "should check the number of the  title's characters" do
      ....
    end
   ...
```

2023-07-14 15:08 UTC, tresorsawasawa commented on app/models/like.rb
>  end
- [ ] As required for the project to have tests to all your models, kindly make sure you also add unit tests to both `Like` and `Comment` models as right now they were not implemented yet.

- [ ] You should also ensure that to add corresponding unit tests to all custom methods in each model such as to the `update_likes_counter` and the `update_comments_counter` methods. This is for the project requirements.

2023-07-14 15:08 UTC, tresorsawasawa commented on spec/models/user_spec.rb
> +
- [ ] As required for the project, kindly ensure that all your tests are passing as right now some of them are failing.
![Screenshot from 2023-07-14 17-06-28](https://github.com/BANCUNGUYE66/Blog-app/assets/83042742/50e73ff5-1462-45d0-af3c-2a64e5d0ca00)

2023-07-15 08:47 UTC, rotimiazeez approved these changes
Hi @BANCUNGUYE66 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job implementing the missing test cases 👍🏽
- All tests passed 💪🏽
- Good PR title/summary 👏🏽

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-15 08:54 UTC, merged

2023-08-17 10:36 UTC, levy002 reviewed
## Hello @BANCUNGUYE66 

Your project is complete!  There is nothing else to say other than... :shipit: 
Congratulations! 🎉 

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._