add controllers
BANCUNGUYE66/Blog-app pull request #4
Opened 2023-07-24 19:15 UTC by BANCUNGUYE66

### create controllers and views for app

For each URL I created:

- [x] A route.
- [x] An action in the correct controller.
- [x] A view file.

2023-07-24 20:24 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @BANCUNGUYE66,

### Nice job, you are almost there.

![cat-driving-serious](https://user-images.githubusercontent.com/68796232/223284600-852bcd90-1495-4a40-8515-cc12636b369b.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [x] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- Nothing to mention.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-07-24 20:24 UTC, Omar-Muhamad commented on app/controllers/navigation_controller.rb
> +end
- [ ] As per project [requirements](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Setup_Controllers_project_v1_1.md#project-requirements), as per the this image:

![image](https://github.com/BANCUNGUYE66/Blog-app/assets/68796232/e645207d-8a7b-46fd-85c5-754381e56d0e)

Please delete what you did here and create 2 controllers with 4 methods, 4 views, and 4 routes one for each method:
- Users controller with index and show methods.
- Posts controller with index and show methods.
don't forget to add a view and route for each method and also don't use `rails generate scaffold` command as you did with the navigation controller.

2023-07-25 08:51 UTC, bobb-Rob approved these changes
## STATUS: APPROVED ✔️ 🍾 🍾 🍾 🥳 🥳 🥳 

Hi @BANCUNGUYE66 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://camo.githubusercontent.com/2c67944c14f5c74b9b607df18d73efb0c423dd148b3e10cb75b445a00220332e/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f5061536e555a573145657970756c734f77642f67697068792e676966)

## Highlights
✅ All linters checks are ok
✅ The correct workflow is used. 
✅ Very descriptive Pull Request(PR)
✅ Your work is well documented.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 08:54 UTC, merged

2023-08-21 20:59 UTC, levy002 reviewed
## Hello @BANCUNGUYE66 

Your project is complete!  There is nothing else to say other than... congratulations! 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)

## Status: APPROVED :fire:  :fire: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-21 20:59 UTC, levy002 commented on config/routes.rb
> +  get '/posts/:id', to: 'posts#show', as: 'post'
- [OPTIONAL] Hey! You can simplify your routes code like this:

```ruby
resources :users, only: [:index, :show] do
  resources :posts, only: [:index, :show]
end
```

By using the `resources` method with the appropriate options, you can achieve the same routing behavior more concisely. This helps keep your codebase clean and easy to manage. Keep up the good work! 🚀👨‍💻