add views
BANCUNGUYE66/Blog-app pull request #6
Opened 2023-07-26 23:55 UTC by BANCUNGUYE66

### Implement views

- [x] Implement the design from the sneak peek wireframes.
- [x] Use methods that I have created in the [processing data in models].
- [x]  Add some data to database.

2023-07-27 01:27 UTC, BenMukebo requested changes
### Hi @BANCUNGUYE66 

You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!

### To highlight 💪🏻

- No linter errors. ✔️ 
- Gitflow was correctly used.  ✔️   
- Good commit messages ✔️ 
- Professional README ✔️ 
- You have followed  JavaScript best practices. ✔️ 
- Descriptive README file.  ✔️ 
 👍  Good job!


## STATUS: CHANGES REQUESTED  ♻️ 
_Please Check the comments under the review and make all required changes_

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏 💻  
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 01:27 UTC, BenMukebo commented on app/views/posts/index.html.erb
> +</ul>
- [ ] Kindy fix this error that is happening on the post index view, I would strongly suggest you revise the association on your models to solve this

![image](https://github.com/BANCUNGUYE66/Blog-app/assets/79058364/98374c2f-2f72-47e9-b740-6297caf14fc2)

2023-07-27 01:27 UTC, BenMukebo commented on db/seeds.rb
> +end
## [OPTIONAL]
- [ ] As I have said In the comment above kindly revise your association, here in the seed file you are using user_id to associate the post to the User but in your database, the association of the User and the Post is done using the author_id foreigner_key. Kindly revise this and do the same for the Comment

![image](https://github.com/BANCUNGUYE66/Blog-app/assets/79058364/b2d2da96-2dcb-4124-a571-f203338cc624)

2023-07-27 18:17 UTC, franclobo requested changes
Hi @BANCUNGUYE66, 

# Required Changes ♻️

![istockphoto-1079018918-612x612](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/0ea90f08-8ac6-4a05-b94f-1d8824fc58d5)

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

- No linter errors ✔️ 
- Descriptive PR ✔️ 
- Correct Git flow ✔️ 
- Correct views ✔️ 


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-27 18:17 UTC, franclobo commented on app/models/post.rb
- [ ] Well done completing the required changes by the last CR Kindly correct this method 👇🏽 

**Incorrect method**

```ruby
def update_posts_counter
  user.increment!(:posts_counter)
end
```
**Correct method** 
``` ruby
def update_posts_counter
 author.increment!(:posts_counter)
end
``` 

to correct this issue 👇🏽 


```ruby
rails aborted!
NameError: undefined local variable or method `user' for #<Post id: nil, author_id: 1, title: "Rerum eos amet.", text: "Ut voluptatem harum. Nihil pariatur quaerat. Volup...", comments_counter: 0, likes_counter: 0, created_at: "2023-07-27 17:55:37.529987000 +0000", updated_at: "2023-07-27 17:55:37.529987000 +0000">
/home/franclobo/microverse/Blog-app/app/models/post.rb:13:in `update_posts_counter'
/home/franclobo/microverse/Blog-app/db/seeds.rb:22:in `block in <main>'
/home/franclobo/microverse/Blog-app/db/seeds.rb:21:in `times'
/home/franclobo/microverse/Blog-app/db/seeds.rb:21:in `<main>'
Tasks: TOP => db:seed
(See full trace by running task with --trace)
```

2023-07-27 18:17 UTC, franclobo commented on app/views/users/index.html.erb
- **[OPTIONAL]** Kindly add the styles to be similar to the wireframe 👇🏽 

| Wireframe | Your design |
|---|---|
| ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/2e32a0df-cae0-461c-8d02-e1c43b0afa92) | ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/8a6c2406-3577-4880-ab40-ce761c22e108) |

2023-07-27 18:17 UTC, franclobo commented on app/views/users/show.html.erb
- **[OPTIONAL]** Kindly add the styles to be similar to the wireframe 👇🏽 

| Wireframe | Your design |
|---|---|
| ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/e1853db7-77cb-45dc-8d70-3801db483841) | ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/a19b3011-aa17-49f3-bff1-ca231f04eb31) |

2023-07-27 18:17 UTC, franclobo commented on app/views/posts/index.html.erb
- **[OPTIONAL]** KIndly add the styles to be similar to the wireframe 👇🏽 

| Wireframe | Your design |
|---|---|
| ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/50cc2c0a-d8d9-4098-ad44-c12c253c7560) | ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/9670dd13-aa25-4360-8e5c-32498b4ed7bc)

2023-07-27 18:17 UTC, franclobo commented on app/views/posts/show.html.erb
- [ ] Kindly add the styles to be similar to the wireframe 👇🏽 

| Wireframe | Your design |
|---|---|
| ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/39d1bc3a-deb7-4deb-9328-edd9d651ea5d) | ![image](https://github.com/BANCUNGUYE66/Blog-app/assets/58642949/4d4c29fc-6d98-4172-bbf8-a7674796aead) |

2023-07-27 19:37 UTC, Abenezer-Tilahun commented on app/models/post.rb
Fixed.

2023-07-27 19:38 UTC, Abenezer-Tilahun approved these changes
Hi @BANCUNGUYE66 
 
Your project is complete  👍 💯   There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 👏🏻

✔️ No linter errors.
✔️ You used correct Git-Flow.
✔️ Professional README  
✔️ Good Commit Messages
✔️ Good job for Implemented Suggested changes.

## Optional suggestions 
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

2023-07-27 19:39 UTC, merged

2023-08-21 21:27 UTC, iambenkis commented
Hi @BANCUNGUYE66  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request 

- [ ] You have submitted a project that is already merged, Kindly open another Pull request and then ask for a review 


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me `@iambenkis` in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-08-21 21:54 UTC, FrederickMih reviewed
## Hi :raising_hand: :raising_hand: @BANCUNGUYE66 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 

:tada: :champagne: <img src="https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif"  width ="160"><img> :tada: :champagne: 


## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._